rest.useragent.default=debugueandoideas/1.0es


spring.application.name=DebugueandoIdeas
server.port=8081

#Bean
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:bump
spring.datasource.username=sa
spring.datasource.password=password

spring.h2.console.enabled=true
# habilita la consola de h2 en web
# http://localhost:8081/h2
spring.h2.console.path=/h2

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
